be_be_bang_bong = {
    "title": "Bé Bé Bằng Bông",
    "time_signature": "2/4",
    "key_signature": ["C", "", "major", "Cmajor"],
    "vexflow_key_signature": "C",
    "bars": [
        [new Note("C", "", duration="q", octave="4")],
        [new Note("A", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("E", "", duration="q", octave="4")],
        [new Note("E", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("D", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("A", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("D", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("D", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],

    ],
    "lines": [4, 4, 4, 4, 3],
    "path": "img/songs/be_be_bang_bong.png",
}