beo_dat_may_troi = {
    "title": "Bèo Dạt Mây Trôi",
    "time_signature": "2/4",
    "key_signature": ["C", "", "major", "Cmajor"],
    "vexflow_key_signature": "C",
    "bars": [
        [new Note("C", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("E", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("E", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("A", "", duration="q", octave="4")],
        [new Note("E", "", duration="q", octave="4")],
        [new Note("E", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("G", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],
        [new Note("C", "", duration="q", octave="4")],

    ],
    "lines": [4, 4, 4, 4, 3],
    "path": "img/songs/beo_dat_may_troi.png",
}